@startuml
start
:Создать пустой стек и пустой массив слов;
:Добавить в стек корневой узел и пустую строку;
while (Стек не пуст и длина всех слов меньше заданной длины)
  :Извлечь последний элемент из стека;
  if (Узел является концом слова)
    :Добавить слово в массив слов;
  endif
  :Получить все дочерние узлы узла;
  :Перемешать дочерние узлы;
  :Добавить все дочерние узлы в стек;
endwhile
:Объединить все слова в одну строку с использованием разделителя;
:Обрезать строку до заданной длины;
:Вернуть обрезанную строку;
@enduml