@startuml
start
:Создать пустой стек и пустой массив слов;
:Добавить в стек корневой узел и пустую строку;
while (\tСтек не пуст и длина строки\nс разделителем не равна требуемой)
  :Извлечь последний элемент из стека;
   if (\t\t\tУзел является концом слова и\nДлина новой строки будет меньше или равна заданной)
     :Добавить слово в массив слов;
   endif
  :Получить все дочерние узлы узла;
  :Перемешать дочерние узлы;
  :Добавить все дочерние узлы в стек;
endwhile
:Объединить все слова в одну строку с использованием разделителя;
:Вернуть сгенерированную;
@enduml