@startuml
|Client|
start
:вызов generateString(opts);

|GenString|
if (opts не предоставлены) then (да)
    :создать CStringOpts по умолчанию;
else (нет)
    :создать CStringOpts с opts;
endif
:получить длину алфавита и требуемой строки;
:создать buffer, который имеет тип unsigned int Array требуемой длины;
:запросить у Web API crypto случайные значения и записать их в buffer;

:инициализация результирующей строки;
repeat: для каждого значения в buffer
    :рассчитать индекс символа в соответствии с алфавитом;
    :добавить символ к результату;
repeat while (достигнута требуемая длина строки)

|Client|
:вернуть сгенерированную строку;
stop
@enduml
